name: Deploy Prod S3 Bucket

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          terraform init \
                -backend-config="bucket=terraform-state-prod-mw240794" \
                -backend-config="key=s3-bucket/terraform.tfstate" \
                -backend-config="region=us-east-1" \

      - name: Select or Create Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Plan Terraform Changes
        run: terraform plan -var="environment=prod" -var="aws_profile=default" -var="s3_bucket_name=my-prod-bucket"

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve -var="environment=prod" -var="aws_profile=default" -var="s3_bucket_name=my-prod-bucket"
