name: Deploy to Dev 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-dev-mw240794" \
            -backend-config="key=s3-bucket/terraform.tfstate" \
            -backend-config="region=us-east-1" \

      - name: Select or Create Workspace
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Plan Terraform Changes
        run: |
          terraform plan -var="environment=dev" -var="aws_profile=default" -var="s3_bucket_name=my-dev-bucket"

      - name: Apply Terraform Changes
        run: |
          terraform apply -auto-approve -var="environment=dev" -var="aws_profile=default" -var="s3_bucket_name=my-dev-bucket"
